FROM php:8-apache
LABEL description="PHP base image" \
    "com.koalaphils.vendor"="Koala Technologies"

RUN set -eux; \
  apt-get update \
  && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    git \
    imagemagick \
    libcmph0 \
    libedit2 \
    libhashkit2 \
    libjpeg62-turbo \
    libmemcached11 \
    libmemcachedutil2 \
    libmpdec2 \
    libmsgpackc2 \
    libpng16-16 \
    libsodium23 \
    libxpm4 \
    libzip4 \
    netcat \
    unzip \
  ; \
  apt-mark manual '.*' > /dev/null; \
  savedAptMark="$(apt-mark showmanual)"; \
  apt-get install -y --no-install-recommends \
    $PHPIZE_DEPS \
    gettext-base \
    libcmph-dev \
    libcurl4-openssl-dev \
    libedit-dev \
    libicu-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libmagickwand-dev \
    libmemcached-dev \
    libmpdec-dev \
    libmsgpack-dev \
    libpng-dev \
    libsodium-dev \
    libssl-dev \
    libwebp-dev \
    libxml2-dev \
    libxpm-dev \
    libzip-dev \
    libbz2-dev \
    zlib1g-dev \
    ${PHP_EXTRA_BUILD_DEPS:-} \
    ; \
  export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    ; \
  docker-php-ext-configure gd --with-jpeg --with-xpm --with-webp --with-freetype \
    ; \
  docker-php-ext-install -j$(nproc) \
    bcmath \
    bz2 \
    gd \
    gettext \
    intl \
    opcache \
    pdo_mysql \
    sockets \
    zip \
    ; \
  pecl update-channels \
  ; \
  pecl install --onlyreqdeps --nobuild decimal; \
    cd "$(pecl config-get temp_dir)/decimal"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild igbinary; \
    cd "$(pecl config-get temp_dir)/igbinary"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild msgpack; \
    cd "$(pecl config-get temp_dir)/msgpack"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild apcu; \
    cd "$(pecl config-get temp_dir)/apcu"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild imagick; \
    cd "$(pecl config-get temp_dir)/imagick"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild redis; \
    cd "$(pecl config-get temp_dir)/redis"; \
    phpize; \
    ./configure --enable-redis-igbinary --enable-redis-json --enable-redis-msgpack; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild memcached; \
    cd "$(pecl config-get temp_dir)/memcached"; \
    phpize; \
    ./configure --enable-memcached-igbinary --enable-memcached-json --enable-memcached-session --enable-memcached-sasl --enable-memcached-msgpack; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild xdebug; \
    cd "$(pecl config-get temp_dir)/xdebug"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild ev; \
    cd "$(pecl config-get temp_dir)/ev"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  docker-php-ext-enable \
    apcu \
    decimal \
    ev \
    igbinary \
    imagick \
    msgpack \
    opcache \
    redis \
    ; \
  cp /usr/bin/envsubst /usr/local/bin/envsubst; \
  apt-mark auto '.*' > /dev/null; \
  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImport=false; \
  rm -rf /tmp/* ~/.pearrc /var/lib/apt/lists/* /var/cache/*; \
  php --version \
  ; \
  a2enmod \
    buffer \
    expires \
    headers \
    mime_magic \
    remoteip \
    rewrite \
  ;

#Security changes
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
  ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
  ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
  ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=3600|g" $PHP_INI_DIR/php.ini \
  ; sed -i "s|^\(;\)*zlib.output_compression\s*=\s*\(.*\)|zlib.output_compression=On|g" $PHP_INI_DIR/php.ini \
  ; sed -i "s|^ServerSignature\(.*\)|ServerSignature Off|g" $APACHE_CONFDIR/conf-enabled/security.conf \
  ; sed -i "s|^ServerTokens\(.*\)|ServerTokens Prod|g" $APACHE_CONFDIR/conf-enabled/security.conf \
  ; echo "LogFormat \"\\\"%{X-Forwarded-For}i %h\\\" %l %u %t \\\"%r\\\" %>s %O \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\"\" combined" > $APACHE_CONFDIR/conf-available/log_combined.conf \
  ; a2enconf log_combined \
  ;

COPY --from=composer /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/www/html