FROM php:8-apache
LABEL description="PHP base image" \
    version="1.0" \
    "com.koalaphils.vendor"="Koala Technologies"

RUN set -eux; \
  apt-get update \
  && apt-get install --no-install-recommends -y \
    curl \
    git \
    imagemagick \
    libbrotli1 \
    libcmph0 \
    libedit2 \
#    libevent-2.1-6 \
#    libevent-extra-2.1-6 \
#    libevent-openssl-2.1-6 \
#    libevent-pthreads-2.1-6 \
    libhashkit2 \
    libjpeg62-turbo \
    liblz4-1 \
    libmemcached11 \
    libmemcachedutil2 \
    libmsgpackc2 \
    libpng16-16 \
    libsodium23 \
    libuuid1 \
    libxpm4 \
    libzip4 \
    unzip \
  ; \
  apt-mark manual '.*' > /dev/null; \
  savedAptMark="$(apt-mark showmanual)"; \
  apt-get install -y --no-install-recommends \
    $PHPIZE_DEPS \
    gettext-base \
    libbrotli-dev \
    libcmph-dev \
    libcurl4-openssl-dev \
    libedit-dev \
#    libevent-dev \
    libicu-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    liblz4-dev \
    libmagickwand-dev \
    libmemcached-dev \
    libmsgpack-dev \
    libpng-dev \
    libsodium-dev \
    libssl-dev \
    libwebp-dev \
    libxml2-dev \
    libxpm-dev \
    libzip-dev \
    libbz2-dev \
    uuid-dev \
    zlib1g-dev \
    ${PHP_EXTRA_BUILD_DEPS:-} \
    ; \
  export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    ; \
  docker-php-ext-configure gd --with-jpeg --with-xpm --with-webp --with-freetype \
    ; \
  docker-php-ext-install -j$(nproc) \
    bcmath \
    bz2 \
    gd \
    gettext \
    intl \
    opcache \
    pdo_mysql \
    sockets \
    zip \
    ; \
  pecl update-channels \
  ; \
  git clone --recursive --depth=1 https://github.com/krakjoe/apcu.git $(pecl config-get temp_dir)/apcu; \
    cd "$(pecl config-get temp_dir)/apcu"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  git clone --recursive --depth=1 https://github.com/igbinary/igbinary.git $(pecl config-get temp_dir)/igbinary; \
    cd "$(pecl config-get temp_dir)/igbinary"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  git clone --recursive --depth=1 https://github.com/msgpack/msgpack-php.git $(pecl config-get temp_dir)/msgpack; \
    cd "$(pecl config-get temp_dir)/msgpack"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild lzf; \
    cd "$(pecl config-get temp_dir)/LZF"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  git clone --recursive --depth=1 https://github.com/Imagick/imagick.git $(pecl config-get temp_dir)/imagick; \
    cd "$(pecl config-get temp_dir)/imagick"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  git clone --recursive --depth=1 https://github.com/kjdev/php-ext-brotli.git $(pecl config-get temp_dir)/php-ext-brotli; \
    cd "$(pecl config-get temp_dir)/php-ext-brotli"; \
    phpize; \
    ./configure --with-libbrotli; \
    make && make install; \
    cd -; \
#  git clone --recursive --depth=1 https://bitbucket.org/osmanov/pecl-event.git $(pecl config-get temp_dir)/event; \
#    cd "$(pecl config-get temp_dir)/event"; \
#    phpize; \
#    ./configure --with-event-core --with-event-extra --with-event-openssl --with-event-pthreads; \
#    make && make install; \
#    cd -; \
  pecl install --onlyreqdeps --nobuild redis; \
    cd "$(pecl config-get temp_dir)/redis"; \
    phpize; \
    ./configure --enable-redis-igbinary --enable-redis-json --enable-redis-msgpack --with-liblz4=/usr/include/; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild memcached; \
    cd "$(pecl config-get temp_dir)/memcached"; \
    phpize; \
    ./configure --enable-memcached-igbinary --enable-memcached-json --enable-memcached-session --enable-memcached-sasl --enable-memcached-msgpack; \
    make && make install; \
    cd -; \
  pecl install --onlyreqdeps --nobuild uuid; \
    cd "$(pecl config-get temp_dir)/uuid"; \
    phpize; \
    ./configure; \
    make && make install; \
    cd -; \
  docker-php-ext-enable \
    apcu \
#    event \
    igbinary \
    imagick \
    lzf \
    msgpack \
    opcache \
    redis \
    uuid \
    ; \
  cp /usr/bin/envsubst /usr/local/bin/envsubst; \
  apt-mark auto '.*' > /dev/null; \
  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImport=false; \
  rm -rf /tmp/* ~/.pearrc /var/lib/apt/lists/* /var/cache/*; \
  php --version \
  ; \
  a2enmod \
    buffer \
    expires \
    headers \
    mime_magic \
    remoteip \
    rewrite \
  ;

#Security changes
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
  ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" /usr/local/etc/php/php.ini \
  ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" /usr/local/etc/php/php.ini \
  ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=3600|g" /usr/local/etc/php/php.ini \
  ; sed -i "s|^\(;\)*zlib.output_compression\s*=\s*\(.*\)|zlib.output_compression=On|g" /usr/local/etc/php/php.ini \
  ; sed -i "s|^ServerSignature\(.*\)|ServerSignature Off|g" /etc/apache2/conf-enabled/security.conf \
  ; sed -i "s|^ServerTokens\(.*\)|ServerTokens Prod|g" /etc/apache2/conf-enabled/security.conf \
  ; echo "LogFormat \"\\\"%{X-Forwarded-For}i %h\\\" %l %u %t \\\"%r\\\" %>s %O \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\"\" combined" > /etc/apache2/conf-available/log_combined.conf \
  ; a2enconf log_combined \
  ;

COPY --from=composer /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/www/html
